name: Codeberg Sync
on:
  push:
    branches:
      - '**'
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: mirror-repository
        uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: "${{ vars.CODEBERG_REMOTE }}"
          GIT_USERNAME: ${{ vars.CODEBERG_USERNAME }}
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
